# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kathleen Weaver
email: kathleen@kweaver.org
description: > # this means to ignore newlines until "baseurl:"
 Github site for Kathleen Weaver
 I am a retired teacher according to the state of Texas.
 I teach computer science for Johns Hopkins University CTY Online Programs
 Working on the OpenSource project Open Live Writer
 I have a few projects of my own.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: kathweaver
github_username:  kathweaver
facebook: http://facebook.com/kathweaver

# Build settings
markdown: kramdown
